services:
  db:
    image: mysql:8.0
    container_name: soundhub-db
    command: >
      --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: soundhub
      MYSQL_USER: soundhub
      MYSQL_PASSWORD: soundhub
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: soundhub-pma
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: soundfake-frontend
    ports:
      - "4200:443"
    depends_on:
      - backend

  backend:
    build:
      context: ./soundhub
    container_name: soundfake-backend
    ports:
      - "8443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/soundhub
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      STORAGE_BASE_DIR: /app/storage
    volumes:
      - ./soundhub/storage:/app/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  soundhub_storage:
